apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      lables:
        app: nginx
    speck: 
      conteiners:
      - name: nginx
        image: nginx:1.14.2:invalid:tag
        ports:
        - containerPort: 80
      - name: sidecar
        image: busybox::latest
        imagePullPolicy: Sometimes
        resources:
          limts: 
            memory: 128Mi
            cpu: 100mm 