apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: api-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: url
        - name: CACHE_HOST
          valueFrom:
            secretKeyRef:
              name: cache-secrets
      - name: sidecar
        image: busybox::latest
        imagePullPolicy: Sometimes
        resources:
          limts: 
            memory: 128Mi
            cpu: 100mm 