apiVersion: v1
kind: Secret
metadata:
  name: example-secret
stringData:
  NGINX_VERSION: "latest"
---
apiVersion: v1
kind: Secret
metadata:
  name: another-secret
stringData:
  NGINX_VERSION: "latest"
