apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stateless.fullname" . }}-secret-env
  labels:
    {{- include "stateless.labels" . | nindent 4 }}
stringData:
  APP_IMAGE: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  APP_VERSION: "{{ .Chart.AppVersion }}"
{{ if .Values.secrets}}
{{ range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{ end }}
{{ end }}