apiVersion: v1
kind: Service
metadata:
  name: {{ include "stateless.fullname" . }}
  labels:
    {{- include "stateless.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{ range $port := .Values.additionalPorts }}
    - port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{ end }}
  selector:
    {{- include "stateless.selectorLabels" . | nindent 4 }}
