apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: istio-system
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations:
        sidecar.istio.io/inject: "true"  # This will trigger sidecar injection
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: istio-system
spec:
  selector:
    app: test-app
  ports:
  - port: 80
    targetPort: 80