apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-test
  template:
    metadata:
      labels:
        app: rbac-test
    spec:
      serviceAccountName: restricted-sa
      containers:
      - name: kubectl-runner
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            kubectl get pods --all-namespaces
            sleep 10
          done
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi 