apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
  # Intentionally missing permissions for secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
subjects:
- kind: ServiceAccount
  name: nginx-sa
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io 