apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-operator-role
rules:
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules", "gateways"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["security.istio.io"]
  resources: ["authorizationpolicies", "peerauthentications"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
# Intentionally missing permissions for:
# - configmaps (needed for sidecar injection)
# - mutatingwebhookconfigurations (needed for sidecar injection)
# - deployments (needed for proxy deployment)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "stateless.serviceAccountName" . }}
  namespace: istio-operator-missing-perms
roleRef:
  kind: ClusterRole
  name: istio-operator-role
  apiGroup: rbac.authorization.k8s.io 