ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: sre-bench.stage.plural.sh
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: sre-bench-tls
    hosts:
      - sre-bench.stage.plural.sh